export const placeholderReviews = [
    {
        id: 1,
        name: "Ratish S",
        rating: 5,
        comment: "Love the non-veg meals here. The Rs. 200/- meal is a wholesome package with fish curry, chicken fry, kakka irachi and more. Best value for money in Changanassery!",
        date: "2024-11-15",
        source: "Google Maps",
        helpful: 12,
    },
    {
        id: 2,
        name: "Satheesh SR",
        rating: 5,
        comment: "Stayed more than 15 times; best budget friendly rooms with a restaurant and bar close to the bus stand and railway station. Always my first choice when in Changanassery.",
        date: "2024-10-20",
        source: "Google Maps",
        helpful: 8,
    },
    {
        id: 3,
        name: "Minu Menon",
        rating: 5,
        comment: "Nice place, enough seating, good staff and good food. The parking facility is a huge plus. Highly recommended for families!",
        date: "2024-09-10",
        source: "Google Maps",
        helpful: 6,
    },
    {
        id: 4,
        name: "Arun Kumar",
        rating: 4,
        comment: "Good budget hotel near the bus stand. Clean rooms and tasty food. The biryani here is one of the best in town. Will definitely come back.",
        date: "2024-08-25",
        source: "Zomato",
        helpful: 4,
    },
    {
        id: 5,
        name: "Priya Thomas",
        rating: 5,
        comment: "We booked the hall for my daughter's birthday party. The staff was very helpful and the catering was excellent. Great venue for small events!",
        date: "2024-07-12",
        source: "Google Maps",
        helpful: 10,
    },
];
